BWE_HUD = BWE_HUD or {}

local evm = GetEventManager()
local wim = GetWindowManager()
local sf = 1/GetSetting(SETTING_TYPE_UI, UI_SETTING_CUSTOM_SCALE)

local isShielded = false
local isMounted = false
local isWerewolf = false
local usingSiegeWeapon = false

BWE_HUD.playerFrame = {}

function BWE_HUD.CreatePlayerControls()

    local frame = {}

    frame = wim:CreateControl("BWE_PLAYER", BWE_HUD.container, CT_CONTROL)
	frame:SetDimensions(BWE_HUD.SV.player.size.width, BWE_HUD.SV.player.size.height)
	frame:SetAnchor(TOPLEFT, BWE_HUD.container, TOPLEFT, BWE_HUD.SV.player.position.offsetX, BWE_HUD.SV.player.position.offsetY)
    frame:SetMouseEnabled(true)

    frame.statusBar = wim:CreateControl(nil, frame, CT_CONTROL)
    frame.statusBar:SetDimensions(frame:GetDimensions())
    frame.statusBar:SetAnchor(BOTTOM, frame, BOTTOM, 0, -(3*sf))

    frame.healthBG = wim:CreateControl(nil, frame.statusBar, CT_BACKDROP)
    frame.healthBG:SetAnchorFill()
    frame.healthBG:SetDrawLayer(0)
    frame.healthBG:SetDrawLevel(0)
    frame.healthBG:SetCenterColor(0, 0, 0, 0.6)
    frame.healthBG:SetEdgeColor(0, 0, 0, 1)
    frame.healthBG:SetEdgeTexture(nil, 1,1, (2*sf))
    frame.healthBG:SetInheritAlpha(false)

    frame.health = wim:CreateControl(nil, frame.statusBar, CT_STATUSBAR)
    frame.health:SetDimensions(frame.statusBar:GetWidth()-(4*sf), frame.statusBar:GetHeight()-(4*sf))
	frame.health:SetAnchor(TOP, frame.statusBar, TOP, 0, (2*sf))
    frame.health:SetDrawLayer(0)
	frame.health:SetDrawLevel(1)
	frame.health:SetColor(0.4, 0.4, 0.4, 1)
	frame.health:SetBarAlignment(0)
	frame.health:SetMinMax(0, 1000)
    frame.health:SetValue(1000)

    frame.shield = wim:CreateControl(nil, frame.bar, CT_STATUSBAR)
    frame.shield:SetDimensions(frame.bar:GetDimensions())
	frame.shield:SetAnchor(TOP, frame.bar, TOP)
	frame.shield:SetDrawLayer(0)
    frame.shield:SetDrawLevel(2)
	frame.shield:SetColor(0.4, 0.4, 0.4, 1)
	frame.shield:SetBarAlignment(0)
	frame.shield:SetMinMax(0, 1000)
    frame.shield:SetValue(1000)

    frame.gloss = wim:CreateControl(nil, frame.bar, CT_STATUSBAR)
	frame.gloss:SetDimensions(frame.bar:GetDimensions())
	frame.gloss:SetAnchor(TOP, frame.bar, TOP)
	frame.gloss:SetDrawLayer(0)
	frame.gloss:SetDrawLevel(3)
	frame.gloss:SetTexture("EsoUI/Art/Miscellaneous/timerBar_genericFill_gloss.dds")
	frame.gloss:SetTextureCoords(0, 1, 0, 0.8125)
	frame.gloss:SetBarAlignment(0)
	frame.gloss:SetMinMax(0, 1000)
    frame.gloss:SetValue(1000)

    frame.hValue = wim:CreateControl(nil, frame, CT_LABEL)
	frame.hValue:SetAnchor(CENTER, frame.bar, CENTER)
	frame.hValue:SetDrawLayer(1)
	frame.hValue:SetDrawLevel(0)
	frame.hValue:SetHorizontalAlignment(TEXT_ALIGN_CENTER)
	frame.hValue:SetVerticalAlignment(TEXT_ALIGN_BOTTOM)
	frame.hValue:SetAlpha(0.9)
	frame.hValue:SetFont("$(BOLD_FONT)|13|soft-shadow-thick")
    frame.hValue:SetText("18k / 18k 100%")

    frame.stamBG = wim:CreateControl(nil, frame.statusBar, CT_BACKDROP)
    frame.stamBG:SetAnchorFill()
    frame.stamBG:SetDrawLayer(0)
    frame.stamBG:SetDrawLevel(0)
    frame.stamBG:SetCenterColor(0, 0, 0, 0.6)
    frame.stamBG:SetEdgeColor(0, 0, 0, 1)
    frame.stamBG:SetEdgeTexture(nil, 1,1, (2*sf))
    frame.stamBG:SetInheritAlpha(false)

    frame.stam = wim:CreateControl(nil, frame.statusBar, CT_STATUSBAR)
    frame.stam:SetDimensions(frame.statusBar:GetWidth()-(4*sf), frame.statusBar:GetHeight()-(4*sf))
	frame.stam:SetAnchor(TOP, frame.statusBar, TOP, 0, (2*sf))
    frame.stam:SetDrawLayer(0)
	frame.stam:SetDrawLevel(1)
	frame.stam:SetColor(0.4, 0.4, 0.4, 1)
	frame.stam:SetBarAlignment(0)
	frame.stam:SetMinMax(0, 1000)
    frame.stam:SetValue(1000)

    frame.sGloss = wim:CreateControl(nil, frame.bar, CT_STATUSBAR)
	frame.sGloss:SetDimensions(frame.bar:GetDimensions())
	frame.sGloss:SetAnchor(TOP, frame.bar, TOP)
	frame.sGloss:SetDrawLayer(0)
	frame.sGloss:SetDrawLevel(3)
	frame.sGloss:SetTexture("EsoUI/Art/Miscellaneous/timerBar_genericFill_gloss.dds")
	frame.sGloss:SetTextureCoords(0, 1, 0, 0.8125)
	frame.sGloss:SetBarAlignment(0)
	frame.sGloss:SetMinMax(0, 1000)
    frame.sGloss:SetValue(1000)

    frame.sValue = wim:CreateControl(nil, frame, CT_LABEL)
	frame.sValue:SetAnchor(CENTER, frame.bar, CENTER)
	frame.sValue:SetDrawLayer(1)
	frame.sValue:SetDrawLevel(0)
	frame.sValue:SetHorizontalAlignment(TEXT_ALIGN_CENTER)
	frame.sValue:SetVerticalAlignment(TEXT_ALIGN_BOTTOM)
	frame.sValue:SetAlpha(0.9)
	frame.sValue:SetFont("$(BOLD_FONT)|13|soft-shadow-thick")
    frame.sValue:SetText("18k / 18k 100%")

    frame.magBG = wim:CreateControl(nil, frame.statusBar, CT_BACKDROP)
    frame.magBG:SetAnchorFill()
    frame.magBG:SetDrawLayer(0)
    frame.magBG:SetDrawLevel(0)
    frame.magBG:SetCenterColor(0, 0, 0, 0.6)
    frame.magBG:SetEdgeColor(0, 0, 0, 1)
    frame.magBG:SetEdgeTexture(nil, 1,1, (2*sf))
    frame.magBG:SetInheritAlpha(false)

    frame.mag = wim:CreateControl(nil, frame.statusBar, CT_STATUSBAR)
    frame.mag:SetDimensions(frame.statusBar:GetWidth()-(4*sf), frame.statusBar:GetHeight()-(4*sf))
	frame.mag:SetAnchor(TOP, frame.statusBar, TOP, 0, (2*sf))
    frame.mag:SetDrawLayer(0)
	frame.mag:SetDrawLevel(1)
	frame.mag:SetColor(0.4, 0.4, 0.4, 1)
	frame.mag:SetBarAlignment(0)
	frame.mag:SetMinMax(0, 1000)
    frame.mag:SetValue(1000)

    frame.mGloss = wim:CreateControl(nil, frame.bar, CT_STATUSBAR)
	frame.mGloss:SetDimensions(frame.bar:GetDimensions())
	frame.mGloss:SetAnchor(TOP, frame.bar, TOP)
	frame.mGloss:SetDrawLayer(0)
	frame.mGloss:SetDrawLevel(3)
	frame.mGloss:SetTexture("EsoUI/Art/Miscellaneous/timerBar_genericFill_gloss.dds")
	frame.mGloss:SetTextureCoords(0, 1, 0, 0.8125)
	frame.mGloss:SetBarAlignment(0)
	frame.mGloss:SetMinMax(0, 1000)
    frame.mGloss:SetValue(1000)

    frame.mValue = wim:CreateControl(nil, frame, CT_LABEL)
	frame.mValue:SetAnchor(CENTER, frame.bar, CENTER)
	frame.mValue:SetDrawLayer(1)
	frame.mValue:SetDrawLevel(0)
	frame.mValue:SetHorizontalAlignment(TEXT_ALIGN_CENTER)
	frame.mValue:SetVerticalAlignment(TEXT_ALIGN_BOTTOM)
	frame.mValue:SetAlpha(0.9)
	frame.mValue:SetFont("$(BOLD_FONT)|13|soft-shadow-thick")
    frame.mValue:SetText("18k / 18k 100%")

    frame.auxIcon = wim:CreateControl(nil, frame, CT_TEXTURE)
	frame.auxIcon:SetDimensions(BWE_HUD.SV.player.size.height/1.5, BWE_HUD.SV.player.size.height/1.5)
	frame.auxIcon:SetAnchor(TOPRIGHT, frame.player, TOPLEFT, -sf, BWE_HUD.SV.player.size.height/5)
	frame.auxIcon:SetDrawLayer(2)
	frame.auxIcon:SetDrawLevel(0)
    frame.auxIcon:SetTexture("/esoui/art/ava/ava_allianceflag_neutral.dds")

    frame.auxBG = wim:CreateControl(nil, frame.statusBar, CT_BACKDROP)
    frame.auxBG:SetAnchorFill()
    frame.auxBG:SetDrawLayer(0)
    frame.auxBG:SetDrawLevel(0)
    frame.auxBG:SetCenterColor(0, 0, 0, 0.6)
    frame.auxBG:SetEdgeColor(0, 0, 0, 1)
    frame.auxBG:SetEdgeTexture(nil, 1,1, (2*sf))
    frame.auxBG:SetInheritAlpha(false)

    frame.aux = wim:CreateControl(nil, frame.statusBar, CT_STATUSBAR)
    frame.aux:SetDimensions(frame.statusBar:GetWidth()-(4*sf), frame.statusBar:GetHeight()-(4*sf))
	frame.aux:SetAnchor(TOP, frame.statusBar, TOP, 0, (2*sf))
    frame.aux:SetDrawLayer(0)
	frame.aux:SetDrawLevel(1)
	frame.aux:SetColor(0.4, 0.4, 0.4, 1)
	frame.aux:SetBarAlignment(0)
	frame.aux:SetMinMax(0, 1000)
    frame.aux:SetValue(1000)

    frame.auxGloss = wim:CreateControl(nil, frame.bar, CT_STATUSBAR)
	frame.auxGloss:SetDimensions(frame.bar:GetDimensions())
	frame.auxGloss:SetAnchor(TOP, frame.bar, TOP)
	frame.auxGloss:SetDrawLayer(0)
	frame.auxGloss:SetDrawLevel(3)
	frame.auxGloss:SetTexture("EsoUI/Art/Miscellaneous/timerBar_genericFill_gloss.dds")
	frame.auxGloss:SetTextureCoords(0, 1, 0, 0.8125)
	frame.auxGloss:SetBarAlignment(0)
	frame.auxGloss:SetMinMax(0, 1000)
    frame.auxGloss:SetValue(1000)

    BWE_HUD.playerFrame["BWE_Player"] = frame
end